rafamadriz/friendly-snippets

snippets/global.json

I noticed the snippet used the vsnip-specific `${VIM:...}` directive, but the VSCode snippet format supports [special variables](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables) for inserting the current date and time. I thought it would be nice to make the snippet compatible with VSCode
Thanks for the cool plugin!

fix: make the "diso" snippet more portable

---

snippets/haskell.json

when declaring a module, the keyword `module` should be lowercase

fix haskell module snippets

---

package.json

Currently, the global snippets aren't loaded globally for all filetypes in vim-vsnip. Setting the [global filetype](https://github.com/hrsh7th/vim-vsnip/blob/e0b3a6bb28d2418978715942aded4d9a9f2404f5/autoload/vsnip/source.vim#L24) fixes it, though I'm unsure the ramifications on other snippet engines.

Set global language for global snippets

---

snippets/c.json
snippets/cpp.json

- `for`: ordered cursor locations
- `forr`: ordered cursor locations
- `enum`: ordered cursor locations
- added `printf`, `sprintf`, `fprintf` snippets
- added `scanf`, `sscanf`, `fscanf` snippets
- added  `malloc` snippet
- added snippet to define a data type based on struct with typedef (`structt`)
- little improvement to `#inc` snippets
- `for`: ordered cursor locations
- `forr`: ordered cursor locations
- `enum`: ordered cursor locations
- added `printf`, `sprintf`, `fprintf` snippets
- added `scanf`, `sscanf`, `fscanf` snippets
- fix `main` description and improve snippet
- added `cin` snippet
- little improvement to `#inc` snippets

Improve C and C++ snippets

---

snippets/c.json

All other snippets like `for`, `while`, `else if` don't add a newline for the
'{' starting a block. So this just makes it consistent with the rest.

[C] Put the opening brack for the block on the same line as the if-clause

---

snippets/java.json

Changing the prefix to `class` make both `cl` and `class` work.

Use long form for class snippet for better usability

---

snippets/ruby.json

Adds an extra space to the `frozen` snippet, for code style reasons:
```ruby
```
I think this is a more common way to find the comment in most projects. It's also how Rubocop documentation recommends it: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/FrozenStringLiteralComment.

Ruby: update frozen string literal comment

---

README.md
package.json
snippets/r.json

Add snippet support for R and relatedly R Markdown. Uses the same prefix and template as [RStudio snippets](https://github.com/rstudio/rstudio/blob/main/src/gwt/acesupport/snippets/snippets/r.js)

Add R snippets

---

snippets/erb.json

Hi,
I think these two additions are very intuitive to trigger render / exec in .erb files. Especially people coming from UltiSnips will miss these: https://github.com/honza/vim-snippets/blob/master/UltiSnips/eruby.snippets#L30-L40.
Let me know what you think.

Intuitive prefixes for render and exec in .erb files

---

package.json
snippets/latex/latex-snippets.json

Some minor tweaks to latex snippets:
- Update the `\ref` snippets to match the `\label` where there are
defined. _E.g._ if the snippets fixes the label to `\label{fig:$2}`,
the ref should already include the `fig:` and not have it as a
replacable part.
- Removed change of font size in figure and table environments. In my
opinion, these should be left out for the user to change if they want.
The snippets should be as generic as possible (hence no font change)
- Removed reference to deleted file (#59) in `package.json`

Update latex snippets

---

snippets/javascript/react.json

1) removed "import React from 'react" as its no longer needed since oct 2020 (React 17)
2) made rfc export the function created aswell (95% of the time you want to export the function you just created)
3) created a react component where you can specify the name in case you want to use it inside another component
4) added the settername to both fields of the useState function (unfortunately I use LuaSnip which does not support regex transformations), so I couldnt test to have the second field capitalized. It should be hard to do but I didnt want to change something I couldnt test myself, should be TODO though
5) Added $0 to the end of the useState to be in line with the other snippets
6) Divided useEffect into two parts, one with the return statement and one without. Most of the time youre …

Made various changes to the react snippets. 

---

package.json

Embedded Ruby is usually used to embed Ruby in HTML documents. I think it makes sense to make HTML snippets available when in eruby files too.

Add eruby to HTML languages

---

package.json
snippets/frameworks/django/filetemplates.json
snippets/frameworks/django/forms.json
snippets/frameworks/django/imports.json
snippets/frameworks/django/models.json
snippets/frameworks/django/views.json

Added Django Snippets on frameworks directory under these 5 files:
1- models: all django models related snippets
2- forms: all django forms related snippets
3- views: all django views related snippets
4- imports: some important django import snippets
5- file-templates: django file template snippets
these snippets almost cover all django snippets.

Added Django Snippets

---

package.json
snippets/svelte.json

These are the snippets that I copied from [vscode-svelte-snippets](https://github.com/fivethree-team/vscode-svelte-snippets).
Also if we want extend javascript snippets, we could have this in our config
```lua
-- Note this should be before nvim-cmp setup
vim.g.vsnip_filetypes = {
svelte = { "javascript" },
}
```

Add support for svelte

---

snippets/html.json

Since all void elements are not closed and the wiki says that the img tag is not closed this error should have gone unnoticed

Update: do not close void elements (tag <img>)

---

README.md

Hi there! The example in the README for enabling the snippets for a framework in vsnip is incorrect. The `ruby` filetype needs to be extended to include `rails`, not the other way around.
Thanks for making friendly-snippets!

Fix vsnip framework example

---

snippets/rmarkdown.json

Added a pair of double quotes to the date portion, because the Rmarkdown YAML parser would reject the header in it's current form. This PR fixes it.

fixed rmarkdown yaml header, date code now works

---

snippets/latex.json

Current `@{` snippet expands `@{` to `\left\{ \right\\}` in vim-vsnip. Changing `\\\\\\\\` to `\\\\\\` works in both vim-vsnip and LunarVim, so this PR won't make this snippet unusable in LunarVim (#93).
According to vscode (vscode-like snippets should behave same in plugin as that in vscode), four `\` or six `\` should work but eight `\` shouldn't.
Here's the analysis: First we know `}` can be escaped in vscode .
- four `\` case:
json: `\\\\}` -> string: `\\}` -> snippet: `\}` (The last `}` isn't escaped)
- six `\` case:
json: `\\\\\\}` -> string: `\\\}` -> snippet: `\}` (The last `}` is escaped)
- eight `\` case:
json: `\\\\\\\\}` -> string: `\\\\}` -> snippet: `\\}` (The last `}` isn't escaped)
I don't know why [plugin](https://github.com/L3MON4D3/LuaSnip) used by LunarVim has …

fix(latex): fix `@{` snippet

---

snippets/shell.json

I use neovim v0.6.1, nvim-packer, nvim-cmp, LuaSnip together. I am sure all are updated to the latest, but i'm having problems from LuaSnip in function `ipairs`. So I did these changes to fix the error. Everything for bash snippets seems to work normal. But I'm not sure if it's right, so please help me check it. Thank you.

Fix luasnip error "ipairs"

---

snippets/plantuml.json

- Add a snippet to provide a basic example UML diagram
- Add a snippet to provide the start/end uml tags 
- Update `plantuml.json` to have an alphabetized structure for the snippets
- Fixed a few typos regarding the word "aggregates"

Update PlantUML Snippets

---

snippets/python/base.json

Looking into issue #124, I realized we could just copy the current snippets and append on the return type annotation. 
So now it would look like this when selecting the snippet for the return type: 
The one above it in the picture is the original snippet already in the snippet collection. A similar approach was done for the methods snippet.
As always, I am open to input from others :sunglasses:

Add 2 Python Snippets to include return type annotation

---

package.json

This change makes the global snippets available in all files when using LuaSnip.
See https://github.com/L3MON4D3/LuaSnip/issues/419.

 Make global snippets available in all files

---

snippets/shell.json

Variables in shell snippets are currently not escaped right, which causes snippets not to expand fully (tested in vim-vsnip). Add escape "\\\\" sequence to $

fix snippets/shell.json

---

snippets/eelixir.json

Typo in the snippet, should be a `$` so that the variable jumping works properly

Fix EElixir for snippet

---

snippets/global.json

Assuming https://github.com/honza/vim-snippets was used as the inspiration for this repo, I change 'datatime' to 'datetime' and removed the 'T' from its body, matching the definition in the original.
I also added an new date snippet for the format common in the United States, as well as a time snippet with seconds.

Fix "datatime" typo and body, and add two more snippets.

---

snippets/javascript/javascript.json

Correcting two broken snippets, `cv` and `cod` weren't working with `${0}`, but they do with `${1}`

Correcting broken snippet for javascript console

---

snippets/plantuml.json

- Removes the use case snippet as any config with brace matching will conflict (and makes this snippet useless)
- Fixes a few prefixes for snippets
- Updates the spacing for the description of the `class` snippet

Plantuml revisions

---

README.md
package.json
snippets/verilog.json

Feature:
- Add some of the basic Verilog snippets. 
Acknowledgements: 
- Since I lack experience with Verilog, these snippets mirror the work maintained in [honza/vim-snippets](https://github.com/honza/vim-snippets/blob/master/snippets/verilog.snippets).
If approved, this will close issue #131

feat: Add verilog snippets

---

package.json

- Corrects the path used in `package.json` for the es7 snippets added in #164  and should resolve issue #171

fix: Corrects path to es7 snippets

---

snippets/cpp.json

I think that doing the while condition before the do body is a better way of setting the snippet.

Change order for do-while snippet

---

snippets/elixir.json

Some of the prefixes inside the elixir file seemed a little odd, so I updated them to more closely match the thing they are trying to achieve, i.e. creating an atom list now has an `al` prefix instead of sharing `wl` with the word list.
Feel free to just close this, if there is some deeper meaning behind this.

Elixir: Align prefixes with inserted code

---

snippets/fortran.json

I mainly removed the `\r` characters. Then I also fixed `sub` and `interf`, made `.true.` and `.false` consistent (lowercase) with the rest of the snippets and removed the unnecessary whitespaces for the if statement conditions.

Improve Fortran snippets

---

snippets/html.json

- Change the jump signature for a couple tags (keeps the user inside the `<html></html>` tags) *
- Format on save (with prettier), simplified the space the snippet file required. 
*Snippets on line 302 and 308 (after prettier formatted the file)

fix issue 194: HTML tag scope Jump

---

package.json

maybe it is necessary to extend hmtl snippet for jsx filetype.
#31
https://github.com/rafamadriz/friendly-snippets/issues/31#issuecomment-1097517567
```lua
require('luasnip').filetype_extend("javascriptreact", { "html" })
```

Html snippets for react && javascriptreact && htmldjango

---

snippets/fennel.json

reason:bsome people have plugins to automatically insert pairs,
this puts two paranthesis at the end
now instead of `(var~)` expanding to
```fennel
(var value))
```
doing `var~` will
```fennel
(var value)
```
this also eliminates the need to put `(` at the beginning

fennel: added leading brackets

---

snippets/lua.json

` "\tlocal ${4:varName} = ${5:{}}\n",`
In the case I use the class snip it will become:
` local temp = value}`
The correct being should be:
` local temp = value`
It seems that the 5th is match `${ 5:{ }` ,which makes a extra "}".
And change `${5:{}}` to `${5:value}` can avoid this problem.

fix(lua): class snip

---

snippets/global.json

Added EUPL license to global snippets. The long lines can also be separated, but I wanted to keep it as original as I could.

add eupl license

---

snippets/frameworks/djangohtml.json

👋 I added jumps where I expect them.
For example in a `for` loop if I jump I expect to finish after the `in` and not at the end of the loop.

Add new jumps to Django templates

---

snippets/ruby.json

This is an attempt to remedy the issues caused in #209 . 
- Renamed the `prefix` for a few snippets to match those of similar structure in the `honza/vim-snippets` repo
- Removed repetitive snippets in the exceptions (which also matched on the word `else`).
- Update your friendly snippets to point at my forks branch
```lua
use { "OkelleyDevelopment/friendly-snippets", branch = "fix-ruby-ifelse" }
-- use { "rafamadriz/friendly-snippets" }
```
- Run `:PackerSync` 
- Test again on a ruby file
Once you're done testing, you can then uncomment the previous repo and re-sync. :sunglasses:

fix: Ruby if-else snippets 

---

snippets/norg.json

see neorg spec: https://github.com/nvim-neorg/norg-specs/blob/3ce2618c1469a8f09a6f0b5dec49d796b022c9ab/1.0-specification.norg#L1327

norg link targets are now set in curly braces instead of normal ones

---

snippets/verilog.json

Updated the snippet to: 
- Correct a typo (`endmoudle` -> `endmodule`)
- Match the snippet formatting as mentioned in #216

fix: Correct Verilog Module Snippet

---

snippets/frameworks/flutter.json

Also fix an issue where state was created as private, resulting in unnecessary warnings.
Super-initializer parameters were introduced in Dart 2.17 and are now the defaults in dart lsp as well.
https://dart.dev/guides/whats-new#may-11-2022-217-release
https://dart.dev/guides/language/language-tour#super-parameters

fix: update stateless & statefull widget snippets

---

snippets/c.json

Make the snippets order more convenient: templates, preprocessor, control flow, loops, functions, types, IO, dynamic allocation, etc.
This order is taken from [honza/vim-snippets](https://github.com/honza/vim-snippets/blob/master/snippets/c.snippets) in order to easily port some snippets from there to here.  
Also such order make it easier for the users to inspect and modify the snippets.

Rearrange the c snippets

---

snippets/c.json

Make preprocessor snippets more verbose and readable, change template snippets so that they make more sense for production code.

fix/add C snippets for templates and preprocessor

---

snippets/norg.json

- Task is now `- ( ) Task` instead of `- [ ] Task` (https://github.com/nvim-neorg/norg-specs/blob/main/1.0-specification.norg#L580-L583)
- Variable is now `&variable&` instead of `=variable=` (https://github.com/nvim-neorg/norg-specs/blob/main/1.0-specification.norg#L1120)
Added:
- inlinecode
- spoiler
- strikethrough
- Sorted all snippets alphabetically

Update neorg snippets

---

snippets/c.json

It's a style/opinion change, but I think one that most people would agree with. I more often see the increment/decrement operator appended rather than prepended, but that's my personal (biased) perspective.
ie.:  `++j` -> `j++` and `--j` -> `j--`
Closes #243

fix(c): Move ++/-- end of variable

---

snippets/elixir.json

Hi, I add the "do" snippet for elixir.
When you try to close the "do end" block always appear the "doc" snippet because is missing the "do" snippet.

feat: add "do" snippet in elixir

---

snippets/quarto.json

I noticed that R was missing from two of the codeblock snippets so I have added them here

Add R to Quarto codeblock snippets

---

snippets/frameworks/vue/javascript.json

the snippet with prefix functionVue3 in vue/javascript.json maybe wrong, there is an extra parenthesis in the code snippet

fix: fix vue/javascript wrong snippet

---

snippets/c.json

Doxygen documentation placeholders now make more sence if unchanged.

(c.json) small usability improvements

---

snippets/markdown.json

Added superscript and subscript snippets for markdown.
Ranging from line number `380-393`.
```diff
- }
+ },
+  "Insert subscript": {
+    "prefix": "sub",
+    "body": [
+      "${1}<sub>${0}"
+    ],
+    "description": "Create a subscript."
+  },
+  "Insert superscript": {
+    "prefix": "sup",
+    "body": [
+      "${1}<sup>${0}"
+    ],
+    "description": "Create a superscript."
+  }
```

added: superscript and subscript snippets

---

snippets/go.json

You don't need to compare bool variables with true or false, you can use `variable` or `!variable` itself.
```golang
if _, ok := map[key]; ok {
}
```
And actually this way of checking if there is key in map is more common in go than `ok == true`, see for example [this answer](https://stackoverflow.com/a/2050629).

fix: golang om snippet code style

---

snippets/latex/latex-snippets.json

Context: Using LazyVim, LuaSnip, friendly-snippets.
Before: Typing 'sec<cr>Hello123<tab>fooBar' expands to unexpected:
```tex
\section{Hello123} % (fold)
\label{sec:fooBar${1:_}}
% section fooBar${1:_} (end)
```
Now: The snippets takes only one parameter (I don't understand why 2 would be necessary) expands to expected:
```tex
\section{Hello123} % (fold)
\label{sec:hello_}
% section Hello123 (end)
```
Special characters and numbers now get replaced by a single underscore.

fixed 'cha','par','prt','sec','subp','sub','ssub' latex snippets expansion

---

package.json

related to #285.
hello again :wave: :yum: 
actually, i do not know why i wrote this in #285, but the language of Nushell is called `nu`.
`nushell` is just the shell part of it :relieved: 
this PR fixes this typo :wink: 
cheers :yum:

FIX: change the `nushell` language to `nu`

---

snippets/markdown.json

Snippets for Markdown links and images currently lack input hints. In the case of a link:
```
[]()
```
Hints can be added to distinguish where you insert the text, and where you insert the URL.
With hints, the link snippet look like this:
```
[text](url)
```
And the image snippet like so:
```
```

add hints for Markdown links and images

---

snippets/ruby.json

When inserting `# frozen_string_literal: true`, the cursor is at the end of the line. While it isn't set in stone, it's pretty much a standard.
With the change I'd like that the cursor is two lines below, as in:
```
$here
```
Is `""` the right way to add extra lines?
Would that be ok? In my particular case this extra annoying because `<Enter>` extends the comment section.

Ruby: Insert extra line after frozen_string_literal

---

snippets/javascript/jsdoc.json

This PR implements the full specification of TSDoc 3: https://jsdoc.app/
* The 62 keywords of JSDoc, with their original comments. Most of them including auto completion.
* The 20+ synonyms defined in the specification.
* 2 extra snippets /* and /** for simple and full comment respectively (the same we added for TSDoc).
Clone the project from Zeioth/friendly-snippets and add this to your LuaSnip config
``` lua
-- Enable friently-snippets opt in snippets
require("luasnip").filetype_extend("javascript", { "jsdoc" })
```
Now open any .js file and the snippets should be available.

feat(javascript): jsdoc snippets

---

.github/workflows/format.yml

According to checkoutv3 docs: https://github.com/marketplace/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit

fix(ci): checkout (almost)  always fails

---

snippets/erb.json
snippets/ruby.json

Thanks for keeping this list of snippets. I'm proposing a few improvements to ruby snippets in this PR:
- Add more "stops" to blocks and `if`s snippets, so you can jump through them and fill the whole block.
- Fix an ERB snippet. It would previously end the snippet after adding the `item` and prefill just `item` on the body of the block. Now it will just have a jumpable body to be filled by the user.
- Remove duplicated inline block snippets.
- Update one of the inline block snippets to terminate after the bracket

Add stops to ruby snippets

---

snippets/tcl.json

* changed whitespaces to tabs for multiline snippets so they work for all cases.
* made descriptions one line
* tested all snippets and made fixes for all bugs I noticed
* set $0 to new line for those commands that are not likely to be used inside square brackets to return values, and removed newline for those that are

Organize tcl snippets

---

package.json
snippets/shell/shell.json
snippets/shell/shelldoc.json

This PR implements the [full specification of google styling guide for shell](https://google.github.io/styleguide/shellguide.html#s4-comments).
* 1 shebang snippet `!/usr/bin/env` with auto completion.
* 2 shelldoc comments for shell functions, with auto completion.

feat(shelldoc)

---

snippets/lua/luadoc.json

Luadoc actually tell us to use this format for comments. This makes the first line be the briefing.

fix(luadoc) comments format

---

snippets/c/cdoc.json
snippets/cpp/cppdoc.json
snippets/java/javadoc.json
snippets/lua/luadoc.json
snippets/php/phpdoc.json
snippets/python/pydoc.json

This PR is the same as  #344 but we apply it to all languages (not only cpp).
It also includes the typo fix originally included in #341. In other words, we are applying all doc related typo fixes in this single PR, which should make it easier to review.
Thank you so much @surmish and @REmerald for reporting 🔥

fix(doc) Typos for all languages

---

snippets/frameworks/djangohtml.json

There are a few use cases in Django for using "blocktrans" tags in a single line (despite the "block" in the name).
Unfortunately, the provided snippet for the block inserts line breaks.
I created a copy of this snipped with a similar name for inserting single-line block tag pairs.

feat(djangohtml): add snippet for blocktrans in a single line

---

snippets/tcl.json

Else doesn't take in a conditional expression

Fix snippet for 'else'

---

snippets/gdscript.json

The match statement was incorrect in multiple ways. This updates it so that it actually reflects the match statement as specified in godot's documentation: https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#match

fix(gdscript): update match snippet

---

snippets/latex.json
snippets/latex/latex-snippets.json

Description:
I noticed some snippets that included label-caption couples made chktex give warnings regarding the warning 24 [Delete this space to maintain correct page references.]. Therefore, i made the necessary changes to improve the usability of the snippets.  
I think this is major issue, because of the heavy use of snippets in the creating of LaTeX documents.
Thank you for your effort and time! :)

(fix latex): label-caption space chktex warning24

---

snippets/javascript/react-ts.json
snippets/javascript/react.json

Recognized that the "us" snippet wasn't automatically capitalizing the setter function name. Addressed this by implementing a fix that now ensures the setter function is appropriately capitalized.

fix useState snippet to automatically capitalize setter function name

---

snippets/c/c.json

Basically, I changed a few snippets to be more useful/logical and less annoying:
* `,` prefix in starter templates is not necessary, but can be very annoying; changed to `st`
* `*ifi` snippets now don't have a space to let the users put newline instead
* removed ternary operator and 1-arg static_assert snippet, since it's more convenient to type it manually
* improved usability and logic of the 'for' snippets, so they could be used in more situations
* it's better to use `%d` instead of `%i` in scanf/printf
* made placeholder ordering of calloc more logical
* small fixes/improvements, wording corrections, etc.

(c.json) small quality improvements

---

snippets/latex/latex-snippets.json

Calling and expanding "cite" would result in "~\cite{}" in stead of "\cite{}"

Latex: Removed '~' from Cite body

---

snippets/c/c.json

Fixed snprintf() snippet incorrectly inserts sprintf() body

snprintf() snippet incorrectly inserts sprintf() body

---

package.json
snippets/frameworks/blade/blade.json
snippets/frameworks/blade/helpers.json
snippets/frameworks/blade/livewire.json
snippets/frameworks/blade/snippets.json

Hi,
I sorry I forgot about this as I do not often work with Laravel,
I had raised the issue #299 a few month ago. I re-forked the repository and added the blade snippets.
I ran a new minimal Neovim instance and it seems to work for me.
If I recall they are taken from the vscode repo 
https://github.com/onecentlin/laravel-blade-snippets-vscode/tree/master/snippets.
Hope this can improve Laravel devs experience on Vim.
Kind regards

add blade snippets

---

snippets/javascript/react-es7.json

In the specific case of Vite, there's no need to import React.
- rfcv is included in case someone needs the original option without Vite.

Add rfcv for React, compatible with Vite

---

snippets/python/debug.json

useful on remote debugging, especially on slurm

feat(python): add snippet for debugpy remote attach

---

snippets/markdown.json

Added snippets for Github alerts as in webpages.
For reference, here is the article referring to the feature.  
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts
Rendering that will make it look like the picture below,

Added Github Alerts

---

snippets/ruby/ruby.json

Ruby's official debugger [debug](https://github.com/ruby/debug) comes with a `binding.break` method which is similar to `binding.irb` and `binding.pry` ([see](https://github.com/ruby/debug?tab=readme-ov-file#modify-source-code-with-bindingbreak-similar-to-bindingpry-or-bindingirb)). We already have snippets for `binding.irb` and `binding.pry` but we are missing one for `binding.break`.

feat(ruby): add `binding.break` snippet

---

package.json
snippets/purescript.json

I couldn't find any contributing guidelines so the snippets I included are tailored towards my own usage. Compared to Haskell (a very similar language) snippets, these:
- Use 2 spaces instead of tabs
- Use unicode
- Don't include short snippets which I believe are easier to type manually anyways
Tabs are almost never used in PureScript. Unicode symbols are about as prevalent as their ASCII counterparts. Either way, if a user has other preferences it would be solved by a formatter.

Add PureScript snippets

---

snippets/rust/rust.json

It doesn't make sense that match defaults to `Some` and `None`...
If you initialize it to `{}` you can use RA code action to `fill in match arms`.

Remove some none

---

snippets/rust/rust.json

Replaced almost all instances of unimplemented! for todo!
https://doc.rust-lang.org/std/macro.unimplemented.html
> todo! conveys an intent of implementing the functionality later and the message is “not yet implemented”, unimplemented! makes no such claims

todo instead of unimplemented

---

package.json
snippets/asciidoc.json

Hello, my suggestion for AsciiDoc snippets. Inspired by pull request #417.
They are based on the [Asciidoctor documentation](https://docs.asciidoctor.org/asciidoc/latest/) and my [personal snippets](https://github.com/tigion/dotfiles/blob/main/nvim/snippets/asciidoc.json).
Not perfect, but I think they are a good start for AsciiDoc snippets.

feat(asciidoc): add snippets

---

package.json
snippets/gleam.json

Add snippet support for Gleam.
The snippets are taken from https://github.com/gleam-lang/vscode-gleam/blob/main/snippets.json.
See issue #418.

feat(gleam): add gleam snippets

---

snippets/terraform.json

This PR adds snippets for the basic building blocks of Terraform ( Data Sources, Input Variables, Resources, Output variables )

feat: add snippets for most basic terraform blocks

---

snippets/javascript/jsdoc.json

Some jsdoc snippets have double curly brackets, but the dollar sign is in the wrong place.

jsdoc: fix double parens

---

snippets/terraform.json

Duplicated key `resource` in terraform snippet cause `vsnip` error in my neovim recently.
Probably because this merge request #426 add new resource key but forgot remove the old one. I deleted the old one because two key doing the same purpose but the new one added by #426 is more verbose and good for readability

fix(terraform): remove duplicate resource snippet

---

snippets/rust/rust.json

After further reviewing of the Rust snippets we include, there were a number that could be removed. I chose a few that were mentioned in the issue and others I saw from testing. The second case was because it's faster to type it out than it was to wait for the snippet engine to load them.
**Notes for reviewers**
- Feel free to suggest others we should remove
- Also suggest if some should remain (that are currently removed).
- Closes 416

416 - Remove some trivial rust snippets

---

snippets/quarto.json

Footnotes are done in pandoc-style, e.g.
```markdown
this is a footnote [^identifier]
[^identifier]: with its description here
```
The identifier must be identical, hence the duplicated tabstop.

add: quarto snippets for footnotes and citations

---

snippets/gitcommit.json

Co-authored-by and Signed-off-by are mentioned in [1].
On-behalf-of is from [2].
[1] https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---trailerlttokengtltvaluegt
[2] https://docs.github.com/en/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-on-behalf-of-an-organization

feat(gitcommit): add common git commit trailers

---

snippets/python/pydoc.json

`"` prefixes cause problems due to autopairs plugins, there're excessive trailing `"` after the inserted snippet.
I changed them to `#` from rdoc.

fix(pydoc): change prefixes from `"` to `#`

---

snippets/latex/latex-snippets.json

This PR fixes the same issue as #359, ie a chktex error (24) having to do with spacing of the label command. The functionality is unchanged, just a reformat.

fix(latex): move label to avoid error

---

snippets/r.json

The previously used module syntax has been deprecated since 2020, see [Mastering Shiny](https://mastering-shiny.org/scaling-modules.html#updated-app) for details.
Thanks!

Update R/`shinymod` snippet

---

snippets/latex/vscode-latex-snippets.json

This PR is in the same spirit as PR #473, addressing further math escaping problems as raised in issue #459.
I **think** this should now capture all LaTeX snippet math-escaping issues of this sort.

fix(latex): address further issues regarding math escaping

---

snippets/kubernetes.json

The Kubernetes 1.21 promotes CronJobs to batch/v1

change kubernetes cronjob api version to v1

---

snippets/latex/latex-snippets.json

https://github.com/user-attachments/assets/6f894c76-c90f-4c43-b074-ed3d97551c67
```json
"\\begin{}…\\end{}": {
"prefix": "begin",
"body": [
"\\\\begin{${1:env}}",
"\t${1/(enumerate|itemize|list)|(description)|(.*)/${1:+\\item }${2:+\\item[] }${3:+ }/}$0",
^^ already tab'd here                                            remove this space ^
"\\\\end{${1:env}}"
],
"description": "Begin - End"
},
```

fix(latex): Fix excess spacing of `begin` snippet

---

snippets/vhdl.json

- removes two duplicate snippets
- removes semicolon in the type snippets, like `std_logic`, as this is already inserted in the signal & co snippets
- adds `gen` to the prefixes where there is a generate statement, which makes it easier to differentiate
- adds snippets for essential things like signal, variable, function and procedure declaration

vhdl: add snippets for conditional assignments, signals, variables, functions, procedures, etc.

---

snippets/python/comprehension.json

This change is motivated by getting better completions when using a language server. When starting from the `iterable` part of the snippet, the language server can infer the type of the values contained in the iterable, so that when we get to the part of writing the `value` it can offer autocompletion and suggestions for fields and methods of `value`.

feat(python): change order of navigation in comprehension snippets

---

snippets/cpp/cpp.json

Just changed a single word that had wrong syntax for snippets I suppose. IDK how to describe it. 
Previously:
```cpp
#ifdef POTATO
std::cout << "Potato\n";
#endif  // DEBUG
````
Now:
```cpp
#ifdef POTATO
std::cout << "Potato\n";
#endif  // POTATO
````

ifdef  conditional compilation directive was not working

---

snippets/PowerShell.json
snippets/cobol/vscode_cobol_jcl.json
snippets/csharp/csharpdoc.json
snippets/fortran.json
snippets/gdscript.json
snippets/objc.json

This PR fixes several languages which (mostly) had typos in snippet `body`. They all resulted in the snippet not having proper syntax.

fix: clean up typos in snippet bodies

---

snippets/javascript/javascript.json

Type 'log' to get the completion 'console.log()'. This is the default console.log in vscode.

console.log snippet with 'log' prefix like in vscode

---

snippets/lua/lua.json

changes made:
- require/io.open: removed quotes since they can also have variables as an argument and user will have choice to use single quotes too
- io.popen: use local scope
- l/ll: description changed to differentiate between declaration and definition
- class: name placeholder changed to `M` because of its popularity
- class: remove variable definition and return statements from body since its not always necessary
- rename `-- code` to empty string to be consistent with other snippets
changes not done in this commit but recommended:
- change `ll` to `local` for ease of typing
- move the quotes in io.open mode arg inside the placeholder (might break the snippet not sure)
- io.open returns file handler not iterator, while loop should probably be removed

lua: fix snippets

---

snippets/javascript/react-es7.json
snippets/javascript/react-native-ts.json
snippets/javascript/react-native.json
snippets/javascript/react-ts.json
snippets/javascript/react.json

https://github.com/rafamadriz/friendly-snippets/issues/523
- removed all "import React from 'React'" snippets. since react 17, importing react like that is no longer needed.
- changed all "import React, { someComponent }" to "import { some Component }" for same reason as above.
**examples of type of changes that happened**
```typescript
// from
"import React from 'react'",
// to - deletion of it
// from
"import React from 'react'",
"",
// to - deletion of it
// from
"import React, { Component } from 'react'",
// to
"import { Component } from 'react'",
```
- fixed all "Compoment" typos with "Component" in javascript/ directory.
replaced with bunch of not formatted spaces because repo owner has different formatting rules it seems. Whenever I formatted, everything would get formatted because …

feat: improved react snippets massively and fixed "Compoment" typos

---

snippets/norg.json

This PR contains two commits to fix #477:
- the first renames the second `single_footnote` snippet key to `ranged_single_footnote`
- the second formats the file using `prettier`

Rename duplicate key in norg.json

---

snippets/csharp/csharp.json
snippets/html.json

Created option for ReadLine to compliment the well-used WriteLine

Add Console.ReadLine snippet for csharp

---

package.json
snippets/ruby/rspec.json

credits to https://github.com/ldrner/rspec-snippets-vscode/blob/26f2865e5e902fdc3fb7f61bd6b20fa7ced56084/snippets/ruby_rspec.json
Adding rspec snippets to ruby, very useful for rspec since this is where snippets are the most useful

feat(ruby): add rspec snippets

---

snippets/global.json

The parenthesis in "c)" cause snippet unselectable by `require("cmp").mapping.select_next_item()` of [nvim-cmp](https://github.com/hrsh7th/nvim-cmp).

fix copyright snippet in global.json

---

snippets/erb.json

Hi,
I'd like to propose adding these two additional `ERB` helpers. I also came across this old [ERB snippet repo](https://github.com/matthewrobertson/ERB-Sublime-Snippets). Tho I don't usually use the other snippets, other people might find them useful. So if ever, we can also include them as well. 
Let me know what you think!

feat(erb): add link_to & comment block snippet

---

snippets/haskell.json

Fix snippt error in lamda snippet
The previous snippt body won't show the correct snippt because a `$` goes right after the forefront backslashs. Ths snippet engine will take this as escape characters.

Fix: haskell's lambda snippet

---

snippets/c/c.json

I added a semicolon at the end of these snippets in c. I'm using neovim with nvim-cmp and friendly-snippets for my school c projects and I'm loving it. However, it was getting tedious to tabout of every printf statement to add a semicolon. Most of the time, a semicolon will always go after a printf statement. The only case I can think of when it doesn't use a semicolon is when it is part of a macro definition like here.
`#define PRINT_MESSAGE(msg) printf("%s", msg)`
I think the same can be applied to all the other snippets but if you don't agree i can change the PR to at the very least include the printf snippet. Here are the snippets i added semicolons to the end of:
```
"puts"
"fputs"
"printf"
"fprintf"
"sprintf"
"snprintf"
"scanf"
"fscanf"
"sscanf"
"malloc"
"calloc"
"realloc" …
```

added semicolons at the end of statements from "puts" to "reallocarray" down the file chronologically

---

snippets/cpp/cpp.json

As discussed in the issue #546, the current C++ Guard snippet doesn't work correctly under Windows. This PR fixes this, while maintaining compatibility with *nix.
I also checked the rest of the snippets, and found no other snippets with this specific problem.

Fixed CPP Include Guard to Work on *nix and Windows
