rafamadriz/friendly-snippets

- package.json
- snippets/global.json
Also as an introduction of global snippets.
> Add global snippet for the current datetimestamp.

- snippets/python/debug.json
python changes to use one line import, added pprint
> Python debug changes and pprint

- README.md
- snippets/java.json
- snippets/sql.json
A file with approximately 50 sql snippets has been added.
Also added the "cl" snippet in java to create:
```java
public class currentFilename {
|
}
```
Example of use with some sql snippets
https://user-images.githubusercontent.com/65829671/117561425-538a8980-b05c-11eb-95cf-9866ee70225b.mp4
Example of use with "cl" in java
https://user-images.githubusercontent.com/65829671/117561161-e8d84e80-b059-11eb-8b0e-6c58b27b9c87.mp4
> Add Snippets for Sql

- README.md
- package.json
- snippets/rails.json
Hi, I added some `Rails` snippets that I usually use. This is not everything yet, I might slowly add in more when I come across other useful snippets.
I raised an [issue](https://github.com/rafamadriz/friendly-snippets/issues/15) earlier, and attempted to fix it in this PR as well. I am not sure whether the fix is okay. Let me know if need more testing or have any better solution. Thanks for this plugin btw :) Was searching for a snippet to use with `compe` and found `vimsnip` and `friendly-snippets` the easiest to setup.
> Add basic rails snippet

- package.json
make friendly-snippets works with coc.nvim/coc-snippets
`CocInstall https://github.com/rafamadriz/friendly-snippets@main`
> feat: add name/engines in package.json

- package.json
- snippets/fennel.json
This commit adds snippets for fennel.
> Add snippet for fennel

- snippets/c.json
format some c snippets and add some new c snippets to make the completion is more useful.
> Update c snippets

- package.json
- snippets/flutter.json
I added and tested snippets for Flutter. Original source: https://github.com/Nash0x7E2/awesome-flutter-snippets.
> Add Flutter snippets

- README.md
- package.json
- snippets/cobol/vscode_cobol-compound.json
- snippets/cobol/vscode_cobol.json
- snippets/cobol/vscode_cobol_dir.json
- snippets/cobol/vscode_cobol_jcl.json
- snippets/fortran/vscode-fortran-support.json
- snippets/jekyll/vscode-jekyll-snippets.json
- snippets/latex/latex-snippets.json
- snippets/latex/vscode-latex-snippets.json
- snippets/latex/vscode-latex-support.json
Code check again. No deletion.
> Add new snippets for latex, cobol, fortran, jekyll. New request

- snippets/javascript/javascript.json
Removing some duplicate snippets:
* setTimeout && Set Timeout Function
* setInterval && Set Interval Function
* While loop && While Statement
* if's statements 
* for's statements
> Remove some duplicate snippets in javascript.json

- package.json
- snippets/twig.json
Snippets for Twig. Mostly copied from `mblode/vscode-twig-language-2`.
I write Twig as part of my day job, so I intend to keep these up to date.
> Twig snippets

- snippets/r.json
Just realized I made a mistake in formatting the timestamp snippet so this fixes it. Sorry about that
> Fix R timestamp snippet

- snippets/global.json
> Add lorem ipsum snippets globally for sentence and paragraph.
Tested on:
- Ubuntu 18.04
- NVIM: v0.6.0-dev+176-g4b3ffde20
> feat(global snippets): add lorem ipsum snippets to use globally

- snippets/c.json
- snippets/cpp.json
> Various fixes for C and C++ snippets

- package.json
- snippets/csharp.json
luasnip not reconize the csharp it reconize cs
i am sorry for breaking some linting
> luasnip fix problem with csharp

- snippets/solidity.json
This file is causing issues as it does not comply with the schema
> Fix  solidity file

- README.md
- package.json
- snippets/rescript.json
Add ReScript snippets. Same template https://github.com/rescript-lang/rescript-vscode/blob/master/snippets.json
> add rescript

- snippets/html.json
> Make Image tag self closing

- package.json
- snippets/org.json
Add snippets for org-mode from [doom-emacs](https://github.com/hlissner/doom-snippets)
> Add orgmode snippets

- snippets/elixir.json
This uses the built-in support for providing placeholder text that can be tabbed through and changed, as well as adds in a final position for the cursor.
Would be happy to add in more snippets too, but figured I'd start with updating these :)
> Add in tabstops, placeholders, and final cursor position for Elixir snippets

- package.json
- snippets/scala.json
It would be great to support Scala. This MR provides basic snippets to start with.
> Add support for Scala

- snippets/javascript/react-ts.json
This PR fixes body in the useState snippet
> Fix useState snippet

- snippets/python/base.json
- snippets/python/python.json
I removed most of the duplicate snippets from issue #102 and renamed the new class snippet prefix which generates the init method to "classi" this should make it visible.
> fixed most of the duplicates from #102

- package.json
- snippets/javascript/react-native-ts.json
- snippets/javascript/react-native.json
- snippets/javascript/react-ts.json
- snippets/javascript/react.json
I have added some React Native snippets. Everything seems to work locally. 
Let me know if you would like anything changing.
Thanks
> Add react native snippets

- snippets/rescript.json
* variables
* types
* decorators
* some Belt.Int fns
* Js.Console
* pipe
> add(rescript): new snippets

- package.json
- snippets/go.json
- snippets/make.json
Add snippet support for Makefile
> feature: add make.json

- package.json
- snippets/dart.json
Source: [Dart-code](https://github.com/Dart-Code/Dart-Code/blob/master/snippets/dart.json)
> adding dart snippets

- package.json
- snippets/objc.json
> feat: add objc.json

- snippets/sql.json
> fix foriegnkc snippet

- package.json
- snippets/frameworks/django/django_rest/serializers.json
- snippets/frameworks/django/django_rest/views.json
- snippets/frameworks/django/filetemplates.json
- snippets/frameworks/django/imports.json
- snippets/frameworks/django/models.json
- snippets/frameworks/django/views.json
Added Django Rest Snippets and Fixed some Django Snippets.
> added django rest snippets

- package.json
- snippets/frameworks/unreal.json
Add snippets for Unreal Engine. Snippets are taken from https://github.com/DasCapschen/ue4-snippets-vs
> Add snippets for Unreal Engine

- snippets/global.json
This is where more global snippets are added
[source](https://github.com/honza/vim-snippets/blob/master/snippets/_.snippets)
> Extending global snippets

- snippets/fennel.json
Disclaimer: I am by no means a fennel programmer so any feedback is appreciated :smile: 
This PR attempts to fix the snippet portion of number #152  
- Snippets are formatted a little better
- Add table declaration 
- Update `set` snippet to be `tset` which is more inline with what fennel docs use
> fix: Update fennel snippets 

- README.md
- package.json
- snippets/javascript/react-es7.json
These snippets are ported from [vscode-react-javascript-snippets](https://github.com/dsznajder/vscode-react-javascript-snippets) and all seem unique from existing snippets in snippets/javascript/*.json
> Add ES7 react, redux, javascript snippets from vscode extension

- snippets/frameworks/vue/html.json
- snippets/frameworks/vue/javascript.json
please update vue composition, it will really help vue developer and this snippet is already over vue snippet in vscode maybe, if you don't believe please see again, thank you
> add pinia and more

- package.json
- snippets/quarto.json
Hi @rafamadriz, here are some code snippets for Quarto. Refer to:
* [Quarto VS Code extension](https://marketplace.visualstudio.com/items?itemName=quarto.quarto)
* [quarto.code-snippets](https://github.com/quarto-dev/quarto-vscode/blob/main/snippets/quarto.code-snippets)
> Add quarto.json

- snippets/frameworks/vue/vue.json
> ➕ add Vue snippets

- snippets/cpp.json
Small changes to control flow snippets. New class snippets added for empty class and qt class
Signed-off-by: Filip Lobpreis <f.lobpreis@gmail.com>
> cpp: changed standard for cpp code snippets

- snippets/cpp.json
> fix cpp.json

- package.json
👋  Hi!
I'm trying to add support to the `htmldjango` filetype.
Let me know what you think about that. I'm new to Neovim.
> Add support for htmldjango in neovim

- snippets/frameworks/django/django_rest/views.json
When debugging issue #210, I have found that the JSON was missing some commas. This PR fixes it so the snippets load as expected :sunglasses:
> Fix django rest views

- package.json
- snippets/java/java-tests.json
Hi,
I'm adding the snippets to help write unit tests in Java.
I've created a new folder for Java, maybe could move the file `java.json` to it.
> Added snippets for Java unit tests

- package.json
- snippets/systemverilog.json
Add snippets for SystemVerilog and UVM, which are useful in IC design/verification.
> Add snippets for SystemVerilog and UVM

- snippets/sql.json
> sql: group by content should't be order by

- snippets/norg.json
Neorg changed some format of their parsers. I might miss some. So please tag me to change
> change the list format

- snippets/c.json
Fix file syntax errors in c.json.
fix https://github.com/rafamadriz/friendly-snippets/issues/233
> fix(c.json): Fix file syntax errors

- snippets/c.json
Improve formatting for these snippets; add some useful snippets.
> improve/add C snippets for control, loops, functions and types

- package.json
- snippets/vhdl.json
Hi!
I added some snippets supporting the VHDL language. The snippets were ported from https://github.com/richjyoung/vscode-modern-vhdl/blob/master/snippets/vhdl.yml
I tested many of them and they do work as intented
> feat: add VHDL support

- package.json
- snippets/fsh.json
Snippets are ported over from the vscode FSH extension: https://github.com/standardhealth/vscode-language-fsh/blob/master/snippets/fsh-snippets.json
> Add snippets for fsh language

- snippets/javascript/javascript.json
- snippets/javascript/typescript.json
Just noticed after my other PR was merged, that I didn't change the descriptions
> Fixes description for For-Await-Of loops

- snippets/kubernetes.json
Not really an important pull request, just to be convenient
> chore: conventional order for configmap

- snippets/frameworks/flutter.json
Also renames `of` to `maybeOf` as of the new flutter standards.
> chore(flutter): update inheritedW left out of #218

- snippets/ruby.json
There is a [new official debug gem](https://github.com/ruby/debug)
it'd be nice if we add it as snippet
> Add official debug gem

- package.json
> Add JSDoc to Javascript file types

- snippets/frameworks/rails.json
Thanks for adding rails and ruby to this snippet collection
> feat(rails): add save_and_open_page

- README.md
Hello,
I had a problem similar to the one presented in #239 and thought I would take a shot at contributing some documentation. Any feedback is greatly appreciated. Thanks.
> Update README.md, per #239

- snippets/cpp.json
Some snippets had "{" in the same line while the others had it in the next line. So, I updated them all to be in the same line for consistency.
> feat(cpp): updated "{" to be in the same line for consistency

- package.json
- snippets/nushell.json
hello there :wave: :yum: 
for the `nushell` language, we have this [`vscode` extension](https://github.com/nushell/vscode-nushell-lang) and these [snippets](https://github.com/nushell/vscode-nushell-lang/blob/main/snippets/nushell.json) :yum: 
it appears you are open to adding more snippets to the collection and i'd love to make the `nushell` ones available to *neovim* :relieved: 
i simply did a copy-paste of the `vscode` snippets file to `snippets/nushell.json` here :+1: 
if there is more to be done, please tell me and i'll correct this PR right away :blush: 
cheers and thanks for all these snippets, really cool :muscle:
> FEATURE: add `nushell` snippets from vscode extension

- README.md
- package.json
- snippets/terraform.json
There is a repository with Terraform snippets for VS Code.
Currently, there are no terraform snippets inside this collection, so I copied and renamed them from [here](https://github.com/rixrix/vscode-terraform-snippets).
> feat: add terraform snippets

- snippets/norg.json
Add new snippets for headings, quotes, lists, tasks, etc. and re-organize most snippets to keep some consistency.
Also update some syntax to latest norg file format specifications changes.
> feat(norg): update snippets

- snippets/javascript/tsdoc.json
This PR contains bugfixes for tsdoc.
> fix(tsdoc): bug fixes

- snippets/latex/latex-snippets.json
Ref: https://stackoverflow.com/a/57383247/12361572
Fix: #297
> fix(latex): begin regex transform

- snippets/javascript/jsdoc.json
This PR contains bugfixes for jsdoc.
> fix(jsdoc): bug fixes

- snippets/gdscript.json
I used the switch statement from the go file as a reference, replacing it with the wording from the official gdscript docs:
https://docs.godotengine.org/en/3.5/tutorials/scripting/gdscript/gdscript_basics.html#match
> feat(gdscript): add match statement snippet

- snippets/javascript/tsdoc.json
Minor fix, just a dot in the wrong place.
> fix(tsdoc): Missing dot

- snippets/javascript/jsdoc.json
> fix(jsdoc) comments format

- package.json
- snippets/tcl.json
Tcl is still used extensively in the Electronic Design Automation space along with Verilog and SystemVerilog. Having snippets for this language would be nice.
> Snippets for the Tcl language

- package.json
- snippets/reason.json
All snippets are from https://github.com/reasonml-editor/vscode-reasonml/blob/8745b53c046e8bf857fa258ad1cb545fba81beaa/snippets/reason.json with some descriptions added.
> feat(reason): Add reason snippets

- snippets/javascript/react-ts.json
Added two new snippets that I use constantly in my work, hopefully will help
> feat: Adding createReactHook and createReactHookWithName snippets

- package.json
- snippets/ocaml/dune-project.json
- snippets/ocaml/dune.json
- snippets/ocaml/ocaml.json
- snippets/ocaml/ocamllex.json
Taken from [OCaml Platform](https://github.com/ocamllabs/vscode-ocaml-platform/blob/master/snippets/) with some descriptions added.
> Add ocaml and dune snippets

- snippets/cpp/cpp.json
added a standard template to cpp.json inspired by the c standard template
> Added a standard template to cpp.json

- snippets/global.json
Added date snippet for DD/MM/YY format; commonly used in Commonwealth nations and Eu.
> global: Added DDMMYY snippet

- snippets/terraform.json
> feat(terraform): add terraform snippets

- snippets/frameworks/edge.json
- Added csrfToken snippet
- Updated csrfField snippet
- Added bouncer ctx
- Added i18n snippets
- Added app.nodeEnvironment snippet
> Updated edge framework snippets

- snippets/cpp/cpp.json
- add header guard
- add casting operations
- add auto function with trailing return
- improve the ergonomics  of try-catch and include statements
> add more cpp snippets.

- snippets/gdscript.json
A before and after.
Tmux pane to the **left** with nvim session running friendly snippets **before** fix
Tmux pane to the **right** with nvim session running friendly snippets **after** fix
https://github.com/rafamadriz/friendly-snippets/assets/44142407/814f0b6d-f182-446a-a96a-7e4000fb1276
> Fixed for range loop in gdscript

- snippets/global.json
Add a UUID (v4) snippet using the `UUID` [variable](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables).
> feat(global): Add UUID snippet

- package.json
- snippets/editorconfig.json
Adds snippets for `.editorconfig` files
> feat(editorconfig): add editorconfig snippets

- snippets/rust/rust.json
```rs
#[cfg(test)]
mod test {
#[test]
fn t() {
todo!();
}
}
```
> feat/mod test 

- package.json
- snippets/beancount.json
Add support for Beancount.
From [vscode-beancount](https://github.com/Lencerf/vscode-beancount)'s [snippet](https://github.com/Lencerf/vscode-beancount/blob/master/snippets/beancount.json). Created by [vlamacko](https://github.com/vlamacko).
> Add Beancount snippets

- snippets/swift.json
It adds a new snippet that write a SwiftUI
> feat: swiftui view snippet

- package.json
- snippets/kivy.json
Kivy is a very popular python framework to build multi platform softwares. This is a snippet of kivy lang an extension used by kivy.
> kivymd snippets has been added to friendly-snippets.

- snippets/tcl.json
Newlines just make for awkward behavior.
> Update tcl.json - remove newlines, not very convenient

- snippets/eelixir.json
Fixed typos in embedded elixir (heex) prefixes
> fix(eelixir): typos in prefixes

- package.json
- snippets/perl.json
Package json should include perl.json reference.
Minor updates to perl
> Update perl snippets

- package.json
- snippets/global.json
- snippets/loremipsum.json
Put "Lorem ipsum" snippets into their own file
Refs: #375
> refactor: move lorem ipsum snippets from global.json

- snippets/vhdl.json
- extend basic types and its initialisation
-  while loop
> feat(vhdl): add multiple snippets

- snippets/rust/rust.json
I've been using these snippets locally for a while, maybe they are friendly enough to be added to the repo as other people working with async Rust may find them useful.
> feat(rust/async-dyn-dispatch): Snippets for async Rust functions

- snippets/latex/vscode-latex-snippets.json
This PR addresses the issue #459. I tested it with Luasnip and the result is expected.
> fix(latex): address issue regarding escaping

- package.json
- snippets/frameworks/remix-ts.json
- add common remix functions
- clean up package.json formatting
> fix: add remix snippets

- snippets/frameworks/djangohtml.json
> fix(djangohtml): fix name placeholder in block tag

- package.json
- snippets/zig.json
Fixes major issues with the pr: #491
> fix: issues with pr #491

- snippets/nix.json
Added `with` snippet and `inherit` snippet
> Add more nix snippets
